export type MedicineCategory =
  | 'Pain & fever' | 'Antibiotics' | 'Diabetes' | 'Heart & blood pressure' | 'Cholesterol' | 'Blood thinners'
  | 'Thyroid' | 'Respiratory & allergy' | 'Stomach & digestion' | 'Mental health' | 'Neurology' | 'Hormones & TRT'
  | 'Vitamins & minerals' | 'Skin' | 'Eyes & ears' | 'Infections (other)' | 'Women’s health' | 'Urology' | 'Bone & joint' | 'Other';

export type Medicine = { name: string; category: MedicineCategory; forms: string[]; use: string };

export const medicineCategories: MedicineCategory[] = [
  'Pain & fever', 'Antibiotics', 'Diabetes', 'Heart & blood pressure', 'Cholesterol', 'Blood thinners', 'Thyroid',
  'Respiratory & allergy', 'Stomach & digestion', 'Mental health', 'Neurology', 'Hormones & TRT', 'Vitamins & minerals',
  'Skin', 'Eyes & ears', 'Infections (other)', 'Women’s health', 'Urology', 'Bone & joint', 'Other',
];

const T = 'Tablet', C = 'Capsule', S = 'Syrup', I = 'Injection', INH = 'Inhaler', CR = 'Cream', D = 'Drops', G = 'Gel', P = 'Patch', SP = 'Spray';

// Generic names only, with the general reason each medicine is used. Doses are intentionally left out: they come from the prescriber.
const rows: [string, MedicineCategory, string[], string][] = [
  ['Paracetamol (acetaminophen)', 'Pain & fever', [T, S, 'Suppository'], 'Mild pain and fever'],
  ['Ibuprofen', 'Pain & fever', [T, S, G], 'Pain, inflammation and fever'],
  ['Diclofenac', 'Pain & fever', [T, G, I], 'Pain and inflammation'],
  ['Naproxen', 'Pain & fever', [T], 'Pain and inflammation'],
  ['Aspirin', 'Pain & fever', [T], 'Pain, fever; low dose for heart protection when prescribed'],
  ['Tramadol', 'Pain & fever', [C, T], 'Moderate to severe pain (prescription)'],
  ['Codeine', 'Pain & fever', [T, S], 'Moderate pain (prescription)'],
  ['Amoxicillin', 'Antibiotics', [C, T, S], 'Bacterial infections'],
  ['Amoxicillin + clavulanic acid', 'Antibiotics', [T, S], 'Bacterial infections'],
  ['Azithromycin', 'Antibiotics', [T, S], 'Bacterial infections'],
  ['Clarithromycin', 'Antibiotics', [T], 'Bacterial infections'],
  ['Ciprofloxacin', 'Antibiotics', [T], 'Bacterial infections, including urinary'],
  ['Cefuroxime', 'Antibiotics', [T, S], 'Bacterial infections'],
  ['Cefixime', 'Antibiotics', [C, S], 'Bacterial infections'],
  ['Doxycycline', 'Antibiotics', [C, T], 'Bacterial infections, acne'],
  ['Metronidazole', 'Antibiotics', [T, G], 'Bacterial and parasitic infections'],
  ['Cotrimoxazole', 'Antibiotics', [T, S], 'Bacterial infections'],
  ['Nitrofurantoin', 'Antibiotics', [C], 'Urinary tract infections'],
  ['Metformin', 'Diabetes', [T], 'Type 2 diabetes'],
  ['Gliclazide', 'Diabetes', [T], 'Type 2 diabetes'],
  ['Glimepiride', 'Diabetes', [T], 'Type 2 diabetes'],
  ['Sitagliptin', 'Diabetes', [T], 'Type 2 diabetes'],
  ['Empagliflozin', 'Diabetes', [T], 'Type 2 diabetes, heart and kidney protection'],
  ['Dapagliflozin', 'Diabetes', [T], 'Type 2 diabetes, heart and kidney protection'],
  ['Insulin glargine', 'Diabetes', [I], 'Long-acting insulin'],
  ['Insulin aspart', 'Diabetes', [I], 'Mealtime insulin'],
  ['Insulin NPH (isophane)', 'Diabetes', [I], 'Intermediate-acting insulin'],
  ['Semaglutide', 'Diabetes', [I, T], 'Type 2 diabetes, weight management'],
  ['Amlodipine', 'Heart & blood pressure', [T], 'High blood pressure, angina'],
  ['Lisinopril', 'Heart & blood pressure', [T], 'High blood pressure, heart failure'],
  ['Enalapril', 'Heart & blood pressure', [T], 'High blood pressure, heart failure'],
  ['Ramipril', 'Heart & blood pressure', [C, T], 'High blood pressure, heart protection'],
  ['Losartan', 'Heart & blood pressure', [T], 'High blood pressure'],
  ['Valsartan', 'Heart & blood pressure', [T], 'High blood pressure, heart failure'],
  ['Bisoprolol', 'Heart & blood pressure', [T], 'High blood pressure, heart failure, rhythm'],
  ['Atenolol', 'Heart & blood pressure', [T], 'High blood pressure, angina'],
  ['Metoprolol', 'Heart & blood pressure', [T], 'High blood pressure, angina, rhythm'],
  ['Hydrochlorothiazide', 'Heart & blood pressure', [T], 'High blood pressure, fluid retention'],
  ['Furosemide', 'Heart & blood pressure', [T, I], 'Fluid retention (diuretic)'],
  ['Spironolactone', 'Heart & blood pressure', [T], 'Heart failure, fluid retention'],
  ['Digoxin', 'Heart & blood pressure', [T], 'Heart failure, atrial fibrillation'],
  ['Glyceryl trinitrate', 'Heart & blood pressure', [SP, T, P], 'Angina relief'],
  ['Atorvastatin', 'Cholesterol', [T], 'High cholesterol'],
  ['Rosuvastatin', 'Cholesterol', [T], 'High cholesterol'],
  ['Simvastatin', 'Cholesterol', [T], 'High cholesterol'],
  ['Ezetimibe', 'Cholesterol', [T], 'High cholesterol'],
  ['Fenofibrate', 'Cholesterol', [C, T], 'High triglycerides'],
  ['Warfarin', 'Blood thinners', [T], 'Prevents blood clots (needs INR monitoring)'],
  ['Acenocoumarol', 'Blood thinners', [T], 'Prevents blood clots (needs INR monitoring)'],
  ['Rivaroxaban', 'Blood thinners', [T], 'Prevents blood clots'],
  ['Apixaban', 'Blood thinners', [T], 'Prevents blood clots'],
  ['Clopidogrel', 'Blood thinners', [T], 'Prevents clots after heart attack or stent'],
  ['Enoxaparin', 'Blood thinners', [I], 'Prevents and treats blood clots'],
  ['Levothyroxine', 'Thyroid', [T], 'Underactive thyroid'],
  ['Carbimazole', 'Thyroid', [T], 'Overactive thyroid'],
  ['Salbutamol', 'Respiratory & allergy', [INH, S, T], 'Asthma and COPD relief'],
  ['Budesonide', 'Respiratory & allergy', [INH, SP], 'Asthma prevention'],
  ['Budesonide + formoterol', 'Respiratory & allergy', [INH], 'Asthma and COPD control'],
  ['Fluticasone', 'Respiratory & allergy', [INH, SP], 'Asthma, allergic rhinitis'],
  ['Montelukast', 'Respiratory & allergy', [T], 'Asthma, allergy'],
  ['Tiotropium', 'Respiratory & allergy', [INH], 'COPD'],
  ['Cetirizine', 'Respiratory & allergy', [T, S], 'Allergies'],
  ['Loratadine', 'Respiratory & allergy', [T, S], 'Allergies'],
  ['Fexofenadine', 'Respiratory & allergy', [T], 'Allergies'],
  ['Prednisolone', 'Respiratory & allergy', [T, S], 'Inflammation, allergy, asthma flare-ups'],
  ['Omeprazole', 'Stomach & digestion', [C, T], 'Acid reflux, ulcers'],
  ['Esomeprazole', 'Stomach & digestion', [T, C], 'Acid reflux, ulcers'],
  ['Pantoprazole', 'Stomach & digestion', [T], 'Acid reflux, ulcers'],
  ['Domperidone', 'Stomach & digestion', [T, S], 'Nausea, bloating'],
  ['Ondansetron', 'Stomach & digestion', [T], 'Nausea and vomiting'],
  ['Loperamide', 'Stomach & digestion', [C], 'Diarrhoea'],
  ['Oral rehydration salts', 'Stomach & digestion', ['Sachet'], 'Dehydration from diarrhoea or vomiting'],
  ['Lactulose', 'Stomach & digestion', [S], 'Constipation'],
  ['Hyoscine butylbromide', 'Stomach & digestion', [T, I], 'Stomach cramps'],
  ['Sertraline', 'Mental health', [T], 'Depression, anxiety'],
  ['Escitalopram', 'Mental health', [T], 'Depression, anxiety'],
  ['Fluoxetine', 'Mental health', [C, T], 'Depression, anxiety, OCD'],
  ['Amitriptyline', 'Mental health', [T], 'Depression, nerve pain'],
  ['Alprazolam', 'Mental health', [T], 'Anxiety (short-term, prescription)'],
  ['Lorazepam', 'Mental health', [T], 'Anxiety (short-term, prescription)'],
  ['Zolpidem', 'Mental health', [T], 'Short-term insomnia'],
  ['Quetiapine', 'Mental health', [T], 'Bipolar disorder, schizophrenia'],
  ['Lithium', 'Mental health', [T], 'Bipolar disorder (needs blood tests)'],
  ['Gabapentin', 'Neurology', [C, T], 'Nerve pain, seizures'],
  ['Pregabalin', 'Neurology', [C], 'Nerve pain, seizures, anxiety'],
  ['Carbamazepine', 'Neurology', [T], 'Epilepsy, trigeminal neuralgia'],
  ['Valproic acid', 'Neurology', [T, S], 'Epilepsy'],
  ['Levetiracetam', 'Neurology', [T, S], 'Epilepsy'],
  ['Sumatriptan', 'Neurology', [T, SP], 'Migraine attacks'],
  ['Levodopa + carbidopa', 'Neurology', [T], 'Parkinson’s disease'],
  ['Testosterone enanthate', 'Hormones & TRT', [I], 'Testosterone replacement therapy (TRT)'],
  ['Testosterone cypionate', 'Hormones & TRT', [I], 'Testosterone replacement therapy (TRT)'],
  ['Testosterone gel', 'Hormones & TRT', [G], 'Testosterone replacement therapy (TRT)'],
  ['Testosterone undecanoate', 'Hormones & TRT', [I, C], 'Testosterone replacement therapy (TRT)'],
  ['Human chorionic gonadotropin (hCG)', 'Hormones & TRT', [I], 'Fertility support alongside TRT, when prescribed'],
  ['Anastrozole', 'Hormones & TRT', [T], 'Estrogen control, breast cancer therapy'],
  ['Estradiol', 'Hormones & TRT', [T, P, G], 'Menopause symptoms, hormone therapy'],
  ['Progesterone', 'Hormones & TRT', [C, G], 'Hormone therapy, cycle support'],
  ['Hydrocortisone', 'Hormones & TRT', [T, CR], 'Adrenal replacement, skin inflammation'],
  ['Vitamin D3 (cholecalciferol)', 'Vitamins & minerals', [C, D, I], 'Vitamin D deficiency'],
  ['Vitamin B12 (cobalamin)', 'Vitamins & minerals', [T, I], 'B12 deficiency'],
  ['Folic acid', 'Vitamins & minerals', [T], 'Folate deficiency, pregnancy'],
  ['Iron (ferrous sulfate)', 'Vitamins & minerals', [T, S], 'Iron-deficiency anaemia'],
  ['Calcium', 'Vitamins & minerals', [T], 'Bone health'],
  ['Magnesium', 'Vitamins & minerals', [T, C], 'Magnesium supplement'],
  ['Zinc', 'Vitamins & minerals', [T, C], 'Zinc supplement'],
  ['Vitamin C', 'Vitamins & minerals', [T], 'Vitamin supplement'],
  ['Omega-3', 'Vitamins & minerals', [C], 'Dietary supplement'],
  ['Multivitamin', 'Vitamins & minerals', [T, C], 'Dietary supplement'],
  ['Hydrocortisone cream', 'Skin', [CR], 'Eczema, itching'],
  ['Betamethasone', 'Skin', [CR], 'Skin inflammation (prescription)'],
  ['Clotrimazole', 'Skin', [CR], 'Fungal skin infections'],
  ['Terbinafine', 'Skin', [CR, T], 'Fungal infections of skin and nails'],
  ['Fusidic acid', 'Skin', [CR], 'Bacterial skin infections'],
  ['Adapalene', 'Skin', [G, CR], 'Acne'],
  ['Isotretinoin', 'Skin', [C], 'Severe acne (specialist prescription)'],
  ['Artificial tears', 'Eyes & ears', [D], 'Dry eyes'],
  ['Timolol', 'Eyes & ears', [D], 'Glaucoma'],
  ['Latanoprost', 'Eyes & ears', [D], 'Glaucoma'],
  ['Chloramphenicol eye', 'Eyes & ears', [D, 'Ointment'], 'Bacterial eye infections'],
  ['Ciprofloxacin ear', 'Eyes & ears', [D], 'Ear infections'],
  ['Fluconazole', 'Infections (other)', [C, T], 'Fungal infections'],
  ['Acyclovir', 'Infections (other)', [T, CR], 'Herpes infections'],
  ['Oseltamivir', 'Infections (other)', [C], 'Influenza'],
  ['Albendazole', 'Infections (other)', [T], 'Intestinal worms'],
  ['Ivermectin', 'Infections (other)', [T], 'Parasitic infections'],
  ['Isoniazid', 'Infections (other)', [T], 'Tuberculosis'],
  ['Rifampicin', 'Infections (other)', [C], 'Tuberculosis'],
  ['Combined oral contraceptive', 'Women’s health', [T], 'Contraception'],
  ['Norethisterone', 'Women’s health', [T], 'Heavy or irregular periods'],
  ['Tranexamic acid', 'Women’s health', [T], 'Heavy periods'],
  ['Clomiphene', 'Women’s health', [T], 'Ovulation induction'],
  ['Mefenamic acid', 'Women’s health', [C, T], 'Period pain'],
  ['Tamsulosin', 'Urology', [C], 'Enlarged prostate'],
  ['Finasteride', 'Urology', [T], 'Enlarged prostate, hair loss'],
  ['Sildenafil', 'Urology', [T], 'Erectile dysfunction'],
  ['Tadalafil', 'Urology', [T], 'Erectile dysfunction, enlarged prostate'],
  ['Oxybutynin', 'Urology', [T], 'Overactive bladder'],
  ['Alendronic acid', 'Bone & joint', [T], 'Osteoporosis'],
  ['Allopurinol', 'Bone & joint', [T], 'Gout prevention'],
  ['Colchicine', 'Bone & joint', [T], 'Gout attacks'],
  ['Methotrexate', 'Bone & joint', [T, I], 'Rheumatoid arthritis, psoriasis (weekly dosing)'],
  ['Glucosamine', 'Bone & joint', [T, C], 'Joint supplement'],
  ['Cyclobenzaprine', 'Bone & joint', [T], 'Muscle spasm'],
  ['Hydroxychloroquine', 'Other', [T], 'Lupus, rheumatoid arthritis, malaria prevention'],
  ['Melatonin', 'Other', [T], 'Sleep support'],
  ['Nicotine replacement', 'Other', [P, 'Gum'], 'Stopping smoking'],
];

export const medicineDirectory: Medicine[] = rows
  .map(([name, category, forms, use]) => ({ name, category, forms, use }))
  .sort((a, b) => a.name.localeCompare(b.name));

export function searchMedicines(query: string, category: MedicineCategory | 'All'): Medicine[] {
  const q = query.trim().toLowerCase();
  return medicineDirectory.filter((m) => (category === 'All' || m.category === category)
    && (!q || m.name.toLowerCase().includes(q) || m.use.toLowerCase().includes(q) || m.category.toLowerCase().includes(q)));
}
