export type GivingVerse = { arabic: string; english: string; source: string };

// Arabic follows the Uthmani script and the English is Sahih International, both via alquran.cloud (Tanzil).
export const givingVerses: GivingVerse[] = [
  { arabic: 'مَّثَلُ ٱلَّذِينَ يُنفِقُونَ أَمْوَٰلَهُمْ فِى سَبِيلِ ٱللَّهِ كَمَثَلِ حَبَّةٍ أَنۢبَتَتْ سَبْعَ سَنَابِلَ فِى كُلِّ سُنۢبُلَةٍۢ مِّا۟ئَةُ حَبَّةٍۢ ۗ وَٱللَّهُ يُضَٰعِفُ لِمَن يَشَآءُ ۗ وَٱللَّهُ وَٰسِعٌ عَلِيمٌ', english: 'The example of those who spend their wealth in the way of Allah is like a seed which grows seven spikes; in each spike is a hundred grains. And Allah multiplies [His reward] for whom He wills. And Allah is all-Encompassing and Knowing.', source: 'Surah Al-Baqarah 2:261' },
  { arabic: 'ٱلَّذِينَ يُنفِقُونَ أَمْوَٰلَهُم بِٱلَّيْلِ وَٱلنَّهَارِ سِرًّۭا وَعَلَانِيَةًۭ فَلَهُمْ أَجْرُهُمْ عِندَ رَبِّهِمْ وَلَا خَوْفٌ عَلَيْهِمْ وَلَا هُمْ يَحْزَنُونَ', english: 'Those who spend their wealth by night and by day, secretly and publicly, they will have their reward with their Lord. And no fear will there be concerning them, nor will they grieve.', source: 'Surah Al-Baqarah 2:274' },
  { arabic: 'قُلْ إِنَّ رَبِّى يَبْسُطُ ٱلرِّزْقَ لِمَن يَشَآءُ مِنْ عِبَادِهِۦ وَيَقْدِرُ لَهُۥ ۚ وَمَآ أَنفَقْتُم مِّن شَىْءٍۢ فَهُوَ يُخْلِفُهُۥ ۖ وَهُوَ خَيْرُ ٱلرَّٰزِقِينَ', english: 'Say, “Indeed, my Lord extends provision for whom He wills of His servants and restricts [it] for him. But whatever you spend of anything, He will replace it; and He is the best of providers.”', source: 'Surah Saba’ 34:39' },
  { arabic: 'إِن تُقْرِضُوا۟ ٱللَّهَ قَرْضًا حَسَنًۭا يُضَٰعِفْهُ لَكُمْ وَيَغْفِرْ لَكُمْ ۚ وَٱللَّهُ شَكُورٌ حَلِيمٌ', english: 'If you loan Allah a goodly loan, He will multiply it for you and forgive you. And Allah is Most Appreciative and Forbearing.', source: 'Surah At-Taghabun 64:17' },
  { arabic: 'إِنَّ ٱلْمُصَّدِّقِينَ وَٱلْمُصَّدِّقَٰتِ وَأَقْرَضُوا۟ ٱللَّهَ قَرْضًا حَسَنًۭا يُضَٰعَفُ لَهُمْ وَلَهُمْ أَجْرٌۭ كَرِيمٌۭ', english: 'Indeed, the men who practice charity and the women who practice charity and [they who] have loaned Allah a goodly loan, it will be multiplied for them, and they will have a noble reward.', source: 'Surah Al-Hadid 57:18' },
  { arabic: 'لَن تَنَالُوا۟ ٱلْبِرَّ حَتَّىٰ تُنفِقُوا۟ مِمَّا تُحِبُّونَ ۚ وَمَا تُنفِقُوا۟ مِن شَىْءٍۢ فَإِنَّ ٱللَّهَ بِهِۦ عَلِيمٌۭ', english: 'Never will you attain the good [reward] until you spend from that which you love. And whatever you spend, indeed, Allah is Knowing of it.', source: 'Surah Al ‘Imran 3:92' },
  { arabic: 'وَمَا تُنفِقُوا۟ مِنْ خَيْرٍۢ يُوَفَّ إِلَيْكُمْ وَأَنتُمْ لَا تُظْلَمُونَ', english: 'And whatever you spend of good, it will be fully repaid to you, and you will not be wronged.', source: 'Surah Al-Baqarah 2:272' },
  { arabic: 'وَمَا تُقَدِّمُوا۟ لِأَنفُسِكُم مِّنْ خَيْرٍۢ تَجِدُوهُ عِندَ ٱللَّهِ ۗ إِنَّ ٱللَّهَ بِمَا تَعْمَلُونَ بَصِيرٌۭ', english: 'And whatever good you put forward for yourselves, you will find it with Allah. Indeed, Allah of what you do, is Seeing.', source: 'Surah Al-Baqarah 2:110' },
  { arabic: 'فَمَن يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًۭا يَرَهُۥ', english: 'So whoever does an atom’s weight of good will see it.', source: 'Surah Az-Zalzalah 99:7' },
];
