alter table public.metric_definitions
  add column if not exists category text not null default 'general'
    check (category in ('cardiovascular', 'metabolic', 'respiratory', 'general'));

alter table public.health_measurements
  add column if not exists context jsonb not null default '{}'::jsonb
    check (jsonb_typeof(context) = 'object');

update public.metric_definitions
set category = case metric_key
  when 'blood_glucose' then 'metabolic'
  when 'inr' then 'cardiovascular'
  else category
end,
display_names = case metric_key
  when 'blood_glucose' then '{"en":"Blood glucose","fr":"Glycémie","ar":"سكر الدم"}'::jsonb
  when 'inr' then '{"en":"INR","fr":"INR","ar":"النسبة المعيارية الدولية (INR)"}'::jsonb
  else display_names
end
where metric_key in ('blood_glucose', 'inr');

insert into public.metric_definitions (metric_key, version, display_names, value_kind, supported_units, value_shape, is_active, category)
values
  ('blood_pressure', 1, '{"en":"Blood pressure","fr":"Tension artérielle","ar":"ضغط الدم"}'::jsonb, 'composite', array['mm Hg'], '{"kind":"composite","fields":[{"key":"systolic","label":"Systolic","unit":"mm Hg"},{"key":"diastolic","label":"Diastolic","unit":"mm Hg"}]}'::jsonb, true, 'cardiovascular'),
  ('resting_heart_rate', 1, '{"en":"Resting heart rate","fr":"Fréquence cardiaque au repos","ar":"معدل نبض القلب أثناء الراحة"}'::jsonb, 'scalar', array['bpm'], '{"kind":"scalar"}'::jsonb, true, 'cardiovascular'),
  ('hba1c', 1, '{"en":"HbA1c","fr":"HbA1c","ar":"الهيموغلوبين السكري (HbA1c)"}'::jsonb, 'scalar', array['%'], '{"kind":"scalar"}'::jsonb, true, 'metabolic'),
  ('spo2', 1, '{"en":"Oxygen saturation","fr":"Saturation en oxygène","ar":"تشبع الأكسجين"}'::jsonb, 'scalar', array['%'], '{"kind":"scalar"}'::jsonb, true, 'respiratory'),
  ('vitamin_d', 1, '{"en":"Vitamin D (25-OH)","fr":"Vitamine D (25-OH)","ar":"فيتامين د (25-OH)"}'::jsonb, 'scalar', array['ng/mL'], '{"kind":"scalar"}'::jsonb, true, 'general')
on conflict (metric_key, version) do update
set display_names = excluded.display_names,
    value_kind = excluded.value_kind,
    supported_units = excluded.supported_units,
    value_shape = excluded.value_shape,
    category = excluded.category;

update public.metric_content_versions
set reference_ranges = case definition.metric_key
  when 'blood_glucose' then '[{"context":"fasting","category":"normal","maximum_mg_dl_exclusive":100},{"context":"fasting","category":"prediabetes screening range","minimum_mg_dl":100,"maximum_mg_dl_inclusive":125},{"context":"fasting","category":"individualized diabetes care-plan range","minimum_mg_dl":80,"maximum_mg_dl":130},{"context":"1-2 hours after meal","category":"individualized diabetes care-plan goal","maximum_mg_dl_exclusive":180}]'::jsonb
  when 'inr' then '[{"context":"unmedicated","category":"typical reference","value_approx":1.0},{"context":"some indications such as DVT or atrial fibrillation","category":"common therapeutic range","minimum":2.0,"maximum":3.0},{"context":"some mechanical heart valves","category":"possible therapeutic range","minimum":2.5,"maximum":3.5}]'::jsonb
  else reference_ranges
end
from public.metric_definitions as definition
where definition.id = metric_content_versions.metric_definition_id
  and definition.metric_key in ('blood_glucose', 'inr')
  and metric_content_versions.status = 'draft';

with content_rows(metric_key, locale, content, reference_ranges, evidence_sources) as (
values
('blood_pressure','en','{"title":"Understanding blood pressure","summary":"Blood pressure records systolic and diastolic pressure in the arteries, in mm Hg.","short_explanation":"The upper number is systolic pressure and the lower number is diastolic pressure. A reading is one moment in time and may need to be repeated.","detailed_explanation":"Blood pressure is affected by measurement technique, activity, stress, medicines, and health conditions. The proposed categories below are a screening framework, not a diagnosis or an individualized treatment target. Diagnosis and care decisions require appropriate repeated measurements and clinician assessment.","how_to_read":"Record both numbers in mm Hg. For a home reading, sit quietly for at least five minutes, keep your back supported and feet flat, and use a correctly sized cuff. Avoid caffeine, smoking, and exercise for 30 minutes beforehand when possible.","entry_guidance":"Enter the systolic and diastolic values shown by the validated monitor. Repeat an unexpected reading after resting and record each reading separately.","safety_note":"Do not change medicine based on this chart. Very high readings with chest pain, shortness of breath, weakness, confusion, or severe headache need urgent medical assessment."}'::jsonb,'[{"category":"normal","systolic_max_exclusive":120,"diastolic_max_exclusive":80},{"category":"elevated","systolic_min":120,"systolic_max":129,"diastolic_max_exclusive":80},{"category":"stage 1 hypertension screening","systolic_min":130,"systolic_max":139,"diastolic_min":80,"diastolic_max":89},{"category":"stage 2 hypertension screening","systolic_min":140,"diastolic_min":90}]'::jsonb,'[{"title":"American Heart Association: Understanding Blood Pressure Readings","url":"https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings"},{"title":"CDC: Measuring Your Blood Pressure","url":"https://www.cdc.gov/high-blood-pressure/measure/index.html"}]'::jsonb),
('blood_pressure','fr','{"title":"Comprendre la tension artérielle","summary":"La tension artérielle enregistre les pressions systolique et diastolique dans les artères, en mm Hg.","short_explanation":"Le chiffre du haut est la pression systolique et celui du bas la pression diastolique. Une mesure représente un instant et peut devoir être répétée.","detailed_explanation":"La tension varie selon la technique de mesure, l’activité, le stress, les médicaments et l’état de santé. Les catégories proposées ci-dessous servent au dépistage; elles ne constituent ni un diagnostic ni une cible thérapeutique individuelle. Les décisions nécessitent des mesures répétées adaptées et l’évaluation d’un professionnel.","how_to_read":"Notez les deux chiffres en mm Hg. À domicile, reposez-vous assis pendant cinq minutes, le dos soutenu et les pieds à plat, avec un brassard adapté. Si possible, évitez caféine, tabac et exercice dans les 30 minutes précédentes.","entry_guidance":"Saisissez les valeurs systolique et diastolique affichées par un appareil validé. Répétez une valeur inattendue après repos et enregistrez chaque mesure séparément.","safety_note":"Ne modifiez pas un traitement selon ce graphique. Une mesure très élevée accompagnée de douleur thoracique, d’essoufflement, de faiblesse, de confusion ou de céphalée intense nécessite une évaluation urgente."}'::jsonb,'[{"category":"normal","systolic_max_exclusive":120,"diastolic_max_exclusive":80},{"category":"elevated","systolic_min":120,"systolic_max":129,"diastolic_max_exclusive":80},{"category":"stage 1 hypertension screening","systolic_min":130,"systolic_max":139,"diastolic_min":80,"diastolic_max":89},{"category":"stage 2 hypertension screening","systolic_min":140,"diastolic_min":90}]'::jsonb,'[{"title":"American Heart Association: Blood Pressure Readings","url":"https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings"},{"title":"CDC: Measuring Your Blood Pressure","url":"https://www.cdc.gov/high-blood-pressure/measure/index.html"}]'::jsonb),
('blood_pressure','ar','{"title":"فهم ضغط الدم","summary":"يسجل ضغط الدم الضغط الانقباضي والانبساطي في الشرايين بوحدة ملم زئبق.","short_explanation":"الرقم العلوي هو الضغط الانقباضي والسفلي هو الضغط الانبساطي. تمثل القراءة لحظة واحدة وقد تحتاج إلى التكرار.","detailed_explanation":"يتأثر ضغط الدم بطريقة القياس والنشاط والتوتر والأدوية والحالة الصحية. التصنيفات المقترحة أدناه إطار للفحص وليست تشخيصًا أو هدف علاج فرديًا. تتطلب القرارات الطبية قياسات مناسبة ومتكررة وتقييم مختص.","how_to_read":"سجل الرقمين بوحدة ملم زئبق. عند القياس في المنزل، اجلس بهدوء خمس دقائق على الأقل مع إسناد الظهر ووضع القدمين على الأرض واستخدام سوار مناسب. تجنب الكافيين والتدخين والرياضة خلال الثلاثين دقيقة السابقة إن أمكن.","entry_guidance":"أدخل الرقمين الانقباضي والانبساطي كما يظهران على الجهاز المعتمد. أعد القياس غير المتوقع بعد الراحة وسجل كل قراءة منفصلة.","safety_note":"لا تغير الدواء اعتمادًا على الرسم وحده. القراءة المرتفعة جدًا مع ألم الصدر أو ضيق التنفس أو الضعف أو الارتباك أو صداع شديد تستلزم تقييمًا عاجلًا."}'::jsonb,'[{"category":"normal","systolic_max_exclusive":120,"diastolic_max_exclusive":80},{"category":"elevated","systolic_min":120,"systolic_max":129,"diastolic_max_exclusive":80},{"category":"stage 1 hypertension screening","systolic_min":130,"systolic_max":139,"diastolic_min":80,"diastolic_max":89},{"category":"stage 2 hypertension screening","systolic_min":140,"diastolic_min":90}]'::jsonb,'[{"title":"American Heart Association: Blood Pressure Readings","url":"https://www.heart.org/en/health-topics/high-blood-pressure/understanding-blood-pressure-readings"},{"title":"CDC: Measuring Your Blood Pressure","url":"https://www.cdc.gov/high-blood-pressure/measure/index.html"}]'::jsonb),
('resting_heart_rate','en','{"title":"Understanding resting heart rate","summary":"Resting heart rate is the number of heartbeats per minute while you are calm and resting.","short_explanation":"A resting pulse can vary with fitness, sleep, stress, illness, medicines, and measurement conditions.","detailed_explanation":"For many adults, a commonly cited resting range is 60 to 100 beats per minute, but fitness and individual health affect what is expected. A single value does not diagnose a heart rhythm problem. Repeated or sudden changes should be interpreted with symptoms and clinical history.","how_to_read":"Measure after sitting or lying quietly. Many people choose the morning before activity. Count beats for a full minute or use a reliable device, and record the time and circumstances.","entry_guidance":"Enter beats per minute (bpm). Repeat an unexpected value when rested and note whether you were ill, stressed, or had recently exercised.","safety_note":"Seek urgent care for a rapid or irregular pulse with fainting, chest pain, severe shortness of breath, or confusion."}'::jsonb,'[{"category":"commonly cited adult resting range","minimum_bpm":60,"maximum_bpm":100},{"category":"may occur in highly trained athletes","minimum_bpm":40,"maximum_bpm":60}]'::jsonb,'[{"title":"American Heart Association: All About Heart Rate","url":"https://www.heart.org/en/healthy-living/fitness/fitness-basics/target-heart-rates"},{"title":"MedlinePlus: Pulse","url":"https://medlineplus.gov/ency/article/003399.htm"}]'::jsonb),
('resting_heart_rate','fr','{"title":"Comprendre la fréquence cardiaque au repos","summary":"La fréquence cardiaque au repos est le nombre de battements par minute lorsque vous êtes calme et au repos.","short_explanation":"Le pouls au repos varie selon la condition physique, le sommeil, le stress, la maladie, les médicaments et les conditions de mesure.","detailed_explanation":"Une plage souvent citée chez l’adulte est de 60 à 100 battements par minute, mais l’entraînement et l’état de santé individuel influencent la valeur attendue. Une mesure isolée ne diagnostique pas un trouble du rythme. Les changements répétés ou soudains doivent être interprétés avec les symptômes et les antécédents.","how_to_read":"Mesurez après vous être reposé assis ou allongé. Beaucoup choisissent le matin avant toute activité. Comptez pendant une minute complète ou utilisez un appareil fiable et notez le contexte.","entry_guidance":"Saisissez les battements par minute (bpm). Répétez une valeur inattendue au repos et notez maladie, stress ou exercice récent.","safety_note":"Consultez en urgence si un pouls rapide ou irrégulier s’accompagne d’un malaise, d’une douleur thoracique, d’un essoufflement sévère ou d’une confusion."}'::jsonb,'[{"category":"commonly cited adult resting range","minimum_bpm":60,"maximum_bpm":100},{"category":"may occur in highly trained athletes","minimum_bpm":40,"maximum_bpm":60}]'::jsonb,'[{"title":"American Heart Association: Heart Rate","url":"https://www.heart.org/en/healthy-living/fitness/fitness-basics/target-heart-rates"},{"title":"MedlinePlus: Pulse","url":"https://medlineplus.gov/ency/article/003399.htm"}]'::jsonb),
('resting_heart_rate','ar','{"title":"فهم معدل نبض القلب أثناء الراحة","summary":"معدل النبض أثناء الراحة هو عدد ضربات القلب في الدقيقة عندما تكون هادئًا ومستريحًا.","short_explanation":"قد يتغير النبض أثناء الراحة بحسب اللياقة والنوم والتوتر والمرض والأدوية وظروف القياس.","detailed_explanation":"يُذكر غالبًا نطاق من 60 إلى 100 ضربة في الدقيقة للبالغين، لكن اللياقة والحالة الصحية الفردية تؤثران في المتوقع. لا تشخّص قراءة واحدة اضطراب نظم القلب. ينبغي تفسير التغيرات المتكررة أو المفاجئة مع الأعراض والتاريخ الصحي.","how_to_read":"قس النبض بعد الجلوس أو الاستلقاء بهدوء. يختار كثيرون الصباح قبل النشاط. احسب النبض دقيقة كاملة أو استخدم جهازًا موثوقًا وسجل الظروف.","entry_guidance":"أدخل عدد الضربات في الدقيقة. أعد القياس غير المتوقع أثناء الراحة وسجل المرض أو التوتر أو الرياضة الحديثة.","safety_note":"اطلب رعاية عاجلة إذا ترافق النبض السريع أو غير المنتظم مع الإغماء أو ألم الصدر أو ضيق التنفس الشديد أو الارتباك."}'::jsonb,'[{"category":"commonly cited adult resting range","minimum_bpm":60,"maximum_bpm":100},{"category":"may occur in highly trained athletes","minimum_bpm":40,"maximum_bpm":60}]'::jsonb,'[{"title":"American Heart Association: Heart Rate","url":"https://www.heart.org/en/healthy-living/fitness/fitness-basics/target-heart-rates"},{"title":"MedlinePlus: Pulse","url":"https://medlineplus.gov/ency/article/003399.htm"}]'::jsonb),
('hba1c','en','{"title":"Understanding HbA1c","summary":"HbA1c estimates average blood glucose over roughly the previous two to three months.","short_explanation":"Unlike a single glucose reading, HbA1c reflects longer-term glucose exposure. It usually does not require fasting.","detailed_explanation":"Common screening categories include below 5.7% and 5.7% to 6.4%; results at or above 6.5% may be used in diagnosis when confirmed and clinically appropriate. A treatment goal such as below 7% is not universal and must be individualized. Conditions affecting red blood cells, pregnancy, and some medical treatments can affect interpretation.","how_to_read":"Enter the percentage from the laboratory report and the collection date. Ask your clinician whether repeat or confirmatory testing is needed.","entry_guidance":"HbA1c generally does not require fasting. Record the exact reported percent and do not compare results from different methods without clinical guidance.","safety_note":"This app does not diagnose diabetes or set a treatment goal. Do not change medicine based only on HbA1c displayed here."}'::jsonb,'[{"category":"common screening reference","maximum_percent_exclusive":5.7},{"category":"common prediabetes screening range","minimum_percent":5.7,"maximum_percent_exclusive":6.5},{"category":"diagnostic threshold that may require confirmation","minimum_percent":6.5},{"category":"example individualized treatment goal, not universal","maximum_percent_exclusive":7.0}]'::jsonb,'[{"title":"CDC: A1C Test for Diabetes and Prediabetes","url":"https://www.cdc.gov/diabetes/diabetes-testing/prediabetes-a1c-test.html"},{"title":"American Diabetes Association: Understanding A1C","url":"https://diabetes.org/about-diabetes/a1c"}]'::jsonb),
('hba1c','fr','{"title":"Comprendre l’HbA1c","summary":"L’HbA1c estime la glycémie moyenne sur les deux à trois derniers mois environ.","short_explanation":"Contrairement à une mesure isolée de glycémie, l’HbA1c reflète une exposition plus longue au glucose. Le jeûne n’est généralement pas nécessaire.","detailed_explanation":"Les catégories de dépistage souvent citées comprennent moins de 5,7 % et 5,7 à 6,4 %; un résultat à partir de 6,5 % peut contribuer au diagnostic s’il est confirmé et adapté au contexte. Un objectif de traitement comme moins de 7 % n’est pas universel et doit être individualisé. Les maladies des globules rouges, la grossesse et certains traitements peuvent modifier l’interprétation.","how_to_read":"Saisissez le pourcentage du compte rendu et la date du prélèvement. Demandez si une confirmation ou un contrôle est nécessaire.","entry_guidance":"L’HbA1c ne nécessite généralement pas de jeûne. Notez le pourcentage exact et ne comparez pas des méthodes différentes sans conseil médical.","safety_note":"Cette application ne diagnostique pas le diabète et ne fixe pas d’objectif de traitement. Ne modifiez pas un médicament selon cette valeur seule."}'::jsonb,'[{"category":"common screening reference","maximum_percent_exclusive":5.7},{"category":"common prediabetes screening range","minimum_percent":5.7,"maximum_percent_exclusive":6.5},{"category":"diagnostic threshold that may require confirmation","minimum_percent":6.5},{"category":"example individualized treatment goal, not universal","maximum_percent_exclusive":7.0}]'::jsonb,'[{"title":"CDC: A1C Test for Diabetes and Prediabetes","url":"https://www.cdc.gov/diabetes/diabetes-testing/prediabetes-a1c-test.html"},{"title":"American Diabetes Association: Understanding A1C","url":"https://diabetes.org/about-diabetes/a1c"}]'::jsonb),
('hba1c','ar','{"title":"فهم HbA1c","summary":"يقدّر HbA1c متوسط سكر الدم خلال الشهرين إلى الثلاثة أشهر الماضية تقريبًا.","short_explanation":"على خلاف قراءة سكر واحدة، يعكس HbA1c التعرض للغلوكوز على مدى أطول. لا يتطلب الفحص الصيام عادةً.","detailed_explanation":"تشمل فئات الفحص الشائعة أقل من 5.7% ومن 5.7 إلى 6.4%. وقد تُستخدم نتيجة 6.5% أو أكثر في التشخيص عند تأكيدها وملاءمتها سريريًا. هدف علاجي مثل أقل من 7% ليس مناسبًا للجميع ويجب تخصيصه. قد تؤثر أمراض خلايا الدم والحمل وبعض العلاجات في التفسير.","how_to_read":"أدخل النسبة المئوية وتاريخ أخذ العينة كما في تقرير المختبر. اسأل الطبيب إن كان الفحص يحتاج إلى إعادة أو تأكيد.","entry_guidance":"لا يتطلب HbA1c الصيام عادةً. سجل النسبة كما وردت ولا تقارن طرق فحص مختلفة دون إرشاد طبي.","safety_note":"لا يشخص هذا التطبيق السكري ولا يحدد هدف العلاج. لا تغير الدواء اعتمادًا على هذه القيمة وحدها."}'::jsonb,'[{"category":"common screening reference","maximum_percent_exclusive":5.7},{"category":"common prediabetes screening range","minimum_percent":5.7,"maximum_percent_exclusive":6.5},{"category":"diagnostic threshold that may require confirmation","minimum_percent":6.5},{"category":"example individualized treatment goal, not universal","maximum_percent_exclusive":7.0}]'::jsonb,'[{"title":"CDC: A1C Test for Diabetes and Prediabetes","url":"https://www.cdc.gov/diabetes/diabetes-testing/prediabetes-a1c-test.html"},{"title":"American Diabetes Association: Understanding A1C","url":"https://diabetes.org/about-diabetes/a1c"}]'::jsonb),
('spo2','en','{"title":"Understanding oxygen saturation","summary":"SpO2 estimates the percentage of oxygen carried by hemoglobin, usually using a fingertip pulse oximeter.","short_explanation":"A home pulse oximeter is an estimate and can be affected by circulation, skin temperature, movement, nail products, and device performance.","detailed_explanation":"Values around 95% to 100% are commonly expected for many people at sea level, but altitude, chronic lung or heart disease, and an individual''s care plan can change the expected level. A number alone is not a diagnosis. Symptoms and repeated readings matter.","how_to_read":"Warm your hand, sit still, remove nail polish if possible, and wait for a stable reading. Record the value and whether you were using prescribed oxygen.","entry_guidance":"Enter the percentage exactly as displayed. If the reading is unexpected, repeat it on another warm finger and consider the device instructions.","safety_note":"Seek urgent care for severe breathing difficulty, blue lips, confusion, or rapidly worsening symptoms regardless of the displayed value. Repeated low readings should be discussed promptly with a clinician."}'::jsonb,'[{"category":"commonly expected for many people at sea level","minimum_percent":95,"maximum_percent":100},{"category":"interpret with symptoms and clinical context","minimum_percent":91,"maximum_percent":94},{"category":"potentially urgent; seek medical advice","maximum_percent":90}]'::jsonb,'[{"title":"FDA: Pulse Oximeter Accuracy and Limitations","url":"https://www.fda.gov/medical-devices/products-and-medical-procedures/pulse-oximeters"},{"title":"MedlinePlus: Pulse Oximetry","url":"https://medlineplus.gov/ency/article/007291.htm"}]'::jsonb),
('spo2','fr','{"title":"Comprendre la saturation en oxygène","summary":"La SpO2 estime la proportion d’oxygène transportée par l’hémoglobine, généralement avec un oxymètre au doigt.","short_explanation":"Un oxymètre à domicile fournit une estimation qui peut varier selon la circulation, la température des doigts, le mouvement, le vernis et l’appareil.","detailed_explanation":"Des valeurs d’environ 95 à 100 % sont souvent attendues chez de nombreuses personnes au niveau de la mer, mais l’altitude, les maladies pulmonaires ou cardiaques et le plan de soins individuel peuvent modifier la valeur attendue. Un chiffre seul ne pose pas de diagnostic. Les symptômes et les mesures répétées comptent.","how_to_read":"Réchauffez votre main, restez immobile, retirez si possible le vernis et attendez une valeur stable. Notez l’utilisation éventuelle d’oxygène prescrit.","entry_guidance":"Saisissez le pourcentage affiché. Si la valeur surprend, recommencez sur un autre doigt chaud et consultez la notice de l’appareil.","safety_note":"Consultez en urgence en cas de difficulté respiratoire sévère, de lèvres bleutées, de confusion ou d’aggravation rapide, quelle que soit la valeur affichée. Discutez rapidement des valeurs basses répétées avec un professionnel."}'::jsonb,'[{"category":"commonly expected for many people at sea level","minimum_percent":95,"maximum_percent":100},{"category":"interpret with symptoms and clinical context","minimum_percent":91,"maximum_percent":94},{"category":"potentially urgent; seek medical advice","maximum_percent":90}]'::jsonb,'[{"title":"FDA: Pulse Oximeter Accuracy and Limitations","url":"https://www.fda.gov/medical-devices/products-and-medical-procedures/pulse-oximeters"},{"title":"MedlinePlus: Pulse Oximetry","url":"https://medlineplus.gov/ency/article/007291.htm"}]'::jsonb),
('spo2','ar','{"title":"فهم تشبع الأكسجين","summary":"تقدّر SpO2 نسبة الأكسجين الذي يحمله الهيموغلوبين، غالبًا باستخدام مقياس التأكسج على الإصبع.","short_explanation":"قراءة جهاز المنزل تقديرية وقد تتأثر بالدورة الدموية وحرارة الأصابع والحركة وطلاء الأظافر ودقة الجهاز.","detailed_explanation":"تُعد قيم نحو 95% إلى 100% شائعة لدى كثير من الناس عند مستوى سطح البحر، لكن الارتفاع عن سطح البحر وأمراض القلب أو الرئة وخطة الرعاية الفردية قد تغير المتوقع. لا تشخّص القيمة وحدها حالة طبية؛ فالأعراض والقراءات المتكررة مهمة.","how_to_read":"دفّئ يدك واجلس دون حركة وأزل طلاء الأظافر إن أمكن وانتظر استقرار القراءة. سجل ما إذا كنت تستخدم أكسجينًا موصوفًا.","entry_guidance":"أدخل النسبة كما تظهر على الجهاز. إذا بدت غير متوقعة، أعدها على إصبع دافئ آخر واتبع تعليمات الجهاز.","safety_note":"اطلب رعاية عاجلة عند صعوبة التنفس الشديدة أو ازرقاق الشفتين أو الارتباك أو التدهور السريع مهما كانت قراءة الجهاز. ناقش القراءات المنخفضة المتكررة سريعًا مع مختص صحي."}'::jsonb,'[{"category":"commonly expected for many people at sea level","minimum_percent":95,"maximum_percent":100},{"category":"interpret with symptoms and clinical context","minimum_percent":91,"maximum_percent":94},{"category":"potentially urgent; seek medical advice","maximum_percent":90}]'::jsonb,'[{"title":"FDA: Pulse Oximeter Accuracy and Limitations","url":"https://www.fda.gov/medical-devices/products-and-medical-procedures/pulse-oximeters"},{"title":"MedlinePlus: Pulse Oximetry","url":"https://medlineplus.gov/ency/article/007291.htm"}]'::jsonb),
('vitamin_d','en','{"title":"Understanding 25-hydroxy vitamin D","summary":"The 25-hydroxy vitamin D blood test is commonly used to assess vitamin D status.","short_explanation":"Results depend on the laboratory method and clinical context. Different organizations may use different thresholds for deficiency or sufficiency.","detailed_explanation":"The proposed categories below are common reference points, not universal targets. Interpretation may depend on bone health, kidney or parathyroid conditions, pregnancy, age, medicines, and the laboratory. A clinician should interpret the result and decide whether supplementation or follow-up is appropriate.","how_to_read":"Record the exact test name, value, unit, date, and laboratory if available. This catalog currently records ng/mL; ask your care team before converting units.","entry_guidance":"Enter a 25-hydroxy vitamin D result, not a different vitamin D test. Do not begin high-dose supplements based only on this chart.","safety_note":"Excess vitamin D supplements can be harmful. Discuss dose and follow-up testing with a clinician, especially if you have kidney disease or take regular medicines."}'::jsonb,'[{"category":"commonly used deficiency threshold","maximum_ng_ml_exclusive":20},{"category":"often described as insufficient","minimum_ng_ml":20,"maximum_ng_ml_exclusive":30},{"category":"commonly considered sufficient in some guidance","minimum_ng_ml":30,"maximum_ng_ml":50},{"category":"possible excess; clinician review needed","minimum_ng_ml":100}]'::jsonb,'[{"title":"NIH Office of Dietary Supplements: Vitamin D","url":"https://ods.od.nih.gov/factsheets/VitaminD-HealthProfessional/"},{"title":"MedlinePlus: 25-hydroxy vitamin D test","url":"https://medlineplus.gov/lab-tests/vitamin-d-test/"}]'::jsonb),
('vitamin_d','fr','{"title":"Comprendre la 25-hydroxyvitamine D","summary":"Le dosage sanguin de 25-hydroxyvitamine D est couramment utilisé pour évaluer le statut en vitamine D.","short_explanation":"Le résultat dépend de la méthode du laboratoire et du contexte clinique. Les organismes peuvent utiliser des seuils différents.","detailed_explanation":"Les catégories proposées ci-dessous sont des repères courants, pas des objectifs universels. L’interprétation peut dépendre de la santé osseuse, des reins ou des parathyroïdes, de la grossesse, de l’âge, des médicaments et du laboratoire. Un professionnel doit interpréter le résultat et décider d’une éventuelle supplémentation ou surveillance.","how_to_read":"Notez le nom exact du test, la valeur, l’unité, la date et le laboratoire si possible. Le catalogue utilise actuellement ng/mL; demandez conseil avant toute conversion.","entry_guidance":"Saisissez un résultat de 25-hydroxyvitamine D, et non un autre dosage. Ne commencez pas de fortes doses de compléments sur la seule base du graphique.","safety_note":"Un excès de compléments de vitamine D peut être nocif. Discutez dose et suivi avec un professionnel, en particulier en cas de maladie rénale ou de traitement régulier."}'::jsonb,'[{"category":"commonly used deficiency threshold","maximum_ng_ml_exclusive":20},{"category":"often described as insufficient","minimum_ng_ml":20,"maximum_ng_ml_exclusive":30},{"category":"commonly considered sufficient in some guidance","minimum_ng_ml":30,"maximum_ng_ml":50},{"category":"possible excess; clinician review needed","minimum_ng_ml":100}]'::jsonb,'[{"title":"NIH Office of Dietary Supplements: Vitamin D","url":"https://ods.od.nih.gov/factsheets/VitaminD-HealthProfessional/"},{"title":"MedlinePlus: 25-hydroxy vitamin D test","url":"https://medlineplus.gov/lab-tests/vitamin-d-test/"}]'::jsonb),
('vitamin_d','ar','{"title":"فهم فحص 25-هيدروكسي فيتامين د","summary":"يُستخدم فحص 25-هيدروكسي فيتامين د في الدم عادةً لتقييم مستوى فيتامين د.","short_explanation":"تعتمد النتيجة على طريقة المختبر والسياق الصحي، وقد تستخدم الجهات المختلفة حدودًا مختلفة للنقص أو الكفاية.","detailed_explanation":"الفئات المقترحة أدناه نقاط مرجعية شائعة وليست أهدافًا عالمية. قد يعتمد التفسير على صحة العظام والكلى والغدد جارات الدرقية والحمل والعمر والأدوية والمختبر. ينبغي للمختص تفسير النتيجة وتحديد الحاجة إلى المكملات أو المتابعة.","how_to_read":"سجل اسم الفحص الدقيق والقيمة والوحدة والتاريخ والمختبر إن توفر. يستخدم هذا السجل حاليًا ng/mL؛ استشر فريق الرعاية قبل تحويل الوحدة.","entry_guidance":"أدخل نتيجة 25-هيدروكسي فيتامين د وليس فحصًا مختلفًا لفيتامين د. لا تبدأ جرعات عالية من المكملات اعتمادًا على الرسم وحده.","safety_note":"قد تضر مكملات فيتامين د الزائدة بالصحة. ناقش الجرعة والمتابعة مع مختص، خاصةً عند وجود مرض كلوي أو استخدام أدوية منتظمة."}'::jsonb,'[{"category":"commonly used deficiency threshold","maximum_ng_ml_exclusive":20},{"category":"often described as insufficient","minimum_ng_ml":20,"maximum_ng_ml_exclusive":30},{"category":"commonly considered sufficient in some guidance","minimum_ng_ml":30,"maximum_ng_ml":50},{"category":"possible excess; clinician review needed","minimum_ng_ml":100}]'::jsonb,'[{"title":"NIH Office of Dietary Supplements: Vitamin D","url":"https://ods.od.nih.gov/factsheets/VitaminD-HealthProfessional/"},{"title":"MedlinePlus: 25-hydroxy vitamin D test","url":"https://medlineplus.gov/lab-tests/vitamin-d-test/"}]'::jsonb)
)
insert into public.metric_content_versions (
  metric_definition_id, locale, content, reference_ranges, evidence_sources, status, authored_by
)
select definition.id, content_rows.locale, content_rows.content, content_rows.reference_ranges,
       content_rows.evidence_sources, 'draft', null
from content_rows
join public.metric_definitions as definition
  on definition.metric_key = content_rows.metric_key
 and definition.version = 1
where not exists (
  select 1 from public.metric_content_versions as existing
  where existing.metric_definition_id = definition.id
    and existing.locale = content_rows.locale
    and existing.status = 'draft'
);